package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table attachment_audit
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class AttachmentAudit implements Serializable {
	/** 状态-未审核*/
	public static final String STATUS_UNDETERMINED = "UNDETERMINED";
	/** 状态-通过*/
	public static final String STATUS_PASS = "PASS";
	/** 状态-驳回*/
	public static final String STATUS_FAIL = "FAIL";
    /**
     * Database Column Remarks:
     *   附件ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_audit.attachment_id
     *
     * @mbg.generated
     */
    private BigInteger attachmentId;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_audit.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_audit.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   状态（未审核：UNDETERMINED，通过：PASS，驳回：FAIL）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_audit.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   审核意见
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_audit.opinion
     *
     * @mbg.generated
     */
    private String opinion;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_audit.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_audit.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment_audit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_audit.attachment_id
     *
     * @return the value of attachment_audit.attachment_id
     *
     * @mbg.generated
     */
    public BigInteger getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_audit.attachment_id
     *
     * @param attachmentId the value for attachment_audit.attachment_id
     *
     * @mbg.generated
     */
    public void setAttachmentId(BigInteger attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_audit.company_id
     *
     * @return the value of attachment_audit.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_audit.company_id
     *
     * @param companyId the value for attachment_audit.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_audit.project_id
     *
     * @return the value of attachment_audit.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_audit.project_id
     *
     * @param projectId the value for attachment_audit.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_audit.status
     *
     * @return the value of attachment_audit.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_audit.status
     *
     * @param status the value for attachment_audit.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_audit.opinion
     *
     * @return the value of attachment_audit.opinion
     *
     * @mbg.generated
     */
    public String getOpinion() {
        return opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_audit.opinion
     *
     * @param opinion the value for attachment_audit.opinion
     *
     * @mbg.generated
     */
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_audit.cst_create
     *
     * @return the value of attachment_audit.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_audit.cst_create
     *
     * @param cstCreate the value for attachment_audit.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_audit.cst_modified
     *
     * @return the value of attachment_audit.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_audit.cst_modified
     *
     * @param cstModified the value for attachment_audit.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_audit
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attachmentId=").append(attachmentId);
        sb.append(", companyId=").append(companyId);
        sb.append(", projectId=").append(projectId);
        sb.append(", status=").append(status);
        sb.append(", opinion=").append(opinion);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}