package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cost_analysis_item_deepen
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CostAnalysisItemDeepen implements Serializable {
	/** 类型-直接成本 */
	public static final String TYPE_DIRECT_COST = "DIRECT_COST";
	/** 类型-间接成本 */
	public static final String TYPE_INDIRECT_COST = "INDIRECT_COST";
	/** 类型-指定分包成本 */
	public static final String TYPE_SUBCONTRACT_COST = "SUBCONTRACT_COST";
	/** 类型-税额 */
	public static final String TYPE_TAX_COST = "TAX_COST";
	public static final List<String> TYPE_LIST = Arrays.asList(new String[] { TYPE_DIRECT_COST, TYPE_INDIRECT_COST,
			TYPE_SUBCONTRACT_COST, TYPE_TAX_COST });
    /**
     * Database Column Remarks:
     *   成本分析项深化ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   成本项名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   成本类型（直接成本：DIRECT_COST，间接成本：INDIRECT_COST，指定分包成本：SUBCONTRACT_COST，税额：TAX_COST）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   单价（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * Database Column Remarks:
     *   成本花费（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.cost
     *
     * @mbg.generated
     */
    private BigDecimal cost;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_analysis_item_deepen.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cost_analysis_item_deepen
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.id
     *
     * @return the value of cost_analysis_item_deepen.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.id
     *
     * @param id the value for cost_analysis_item_deepen.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.company_id
     *
     * @return the value of cost_analysis_item_deepen.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.company_id
     *
     * @param companyId the value for cost_analysis_item_deepen.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.project_id
     *
     * @return the value of cost_analysis_item_deepen.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.project_id
     *
     * @param projectId the value for cost_analysis_item_deepen.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.name
     *
     * @return the value of cost_analysis_item_deepen.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.name
     *
     * @param name the value for cost_analysis_item_deepen.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.type
     *
     * @return the value of cost_analysis_item_deepen.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.type
     *
     * @param type the value for cost_analysis_item_deepen.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.price
     *
     * @return the value of cost_analysis_item_deepen.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.price
     *
     * @param price the value for cost_analysis_item_deepen.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.amount
     *
     * @return the value of cost_analysis_item_deepen.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.amount
     *
     * @param amount the value for cost_analysis_item_deepen.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.unit
     *
     * @return the value of cost_analysis_item_deepen.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.unit
     *
     * @param unit the value for cost_analysis_item_deepen.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.cost
     *
     * @return the value of cost_analysis_item_deepen.cost
     *
     * @mbg.generated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.cost
     *
     * @param cost the value for cost_analysis_item_deepen.cost
     *
     * @mbg.generated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.memo
     *
     * @return the value of cost_analysis_item_deepen.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.memo
     *
     * @param memo the value for cost_analysis_item_deepen.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.cst_create
     *
     * @return the value of cost_analysis_item_deepen.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.cst_create
     *
     * @param cstCreate the value for cost_analysis_item_deepen.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_analysis_item_deepen.cst_modified
     *
     * @return the value of cost_analysis_item_deepen.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_analysis_item_deepen.cst_modified
     *
     * @param cstModified the value for cost_analysis_item_deepen.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_analysis_item_deepen
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", projectId=").append(projectId);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", price=").append(price);
        sb.append(", amount=").append(amount);
        sb.append(", unit=").append(unit);
        sb.append(", cost=").append(cost);
        sb.append(", memo=").append(memo);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}