package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table final_settlement_item
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FinalSettlementItem implements Serializable {
    /**
     * Database Column Remarks:
     *   决算条目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.subproject_name
     *
     * @mbg.generated
     */
    private String subprojectName;

    /**
     * Database Column Remarks:
     *   送审金额（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.submit_money
     *
     * @mbg.generated
     */
    private BigDecimal submitMoney;

    /**
     * Database Column Remarks:
     *   核定金额（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.checked_money
     *
     * @mbg.generated
     */
    private BigDecimal checkedMoney;

    /**
     * Database Column Remarks:
     *   核减金额（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.increased_money
     *
     * @mbg.generated
     */
    private BigDecimal increasedMoney;

    /**
     * Database Column Remarks:
     *   核增金额（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.decreased_money
     *
     * @mbg.generated
     */
    private BigDecimal decreasedMoney;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_settlement_item.is_del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table final_settlement_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.id
     *
     * @return the value of final_settlement_item.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.id
     *
     * @param id the value for final_settlement_item.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.company_id
     *
     * @return the value of final_settlement_item.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.company_id
     *
     * @param companyId the value for final_settlement_item.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.project_id
     *
     * @return the value of final_settlement_item.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.project_id
     *
     * @param projectId the value for final_settlement_item.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.subproject_name
     *
     * @return the value of final_settlement_item.subproject_name
     *
     * @mbg.generated
     */
    public String getSubprojectName() {
        return subprojectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.subproject_name
     *
     * @param subprojectName the value for final_settlement_item.subproject_name
     *
     * @mbg.generated
     */
    public void setSubprojectName(String subprojectName) {
        this.subprojectName = subprojectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.submit_money
     *
     * @return the value of final_settlement_item.submit_money
     *
     * @mbg.generated
     */
    public BigDecimal getSubmitMoney() {
        return submitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.submit_money
     *
     * @param submitMoney the value for final_settlement_item.submit_money
     *
     * @mbg.generated
     */
    public void setSubmitMoney(BigDecimal submitMoney) {
        this.submitMoney = submitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.checked_money
     *
     * @return the value of final_settlement_item.checked_money
     *
     * @mbg.generated
     */
    public BigDecimal getCheckedMoney() {
        return checkedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.checked_money
     *
     * @param checkedMoney the value for final_settlement_item.checked_money
     *
     * @mbg.generated
     */
    public void setCheckedMoney(BigDecimal checkedMoney) {
        this.checkedMoney = checkedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.increased_money
     *
     * @return the value of final_settlement_item.increased_money
     *
     * @mbg.generated
     */
    public BigDecimal getIncreasedMoney() {
        return increasedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.increased_money
     *
     * @param increasedMoney the value for final_settlement_item.increased_money
     *
     * @mbg.generated
     */
    public void setIncreasedMoney(BigDecimal increasedMoney) {
        this.increasedMoney = increasedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.decreased_money
     *
     * @return the value of final_settlement_item.decreased_money
     *
     * @mbg.generated
     */
    public BigDecimal getDecreasedMoney() {
        return decreasedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.decreased_money
     *
     * @param decreasedMoney the value for final_settlement_item.decreased_money
     *
     * @mbg.generated
     */
    public void setDecreasedMoney(BigDecimal decreasedMoney) {
        this.decreasedMoney = decreasedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.cst_create
     *
     * @return the value of final_settlement_item.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.cst_create
     *
     * @param cstCreate the value for final_settlement_item.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.cst_modified
     *
     * @return the value of final_settlement_item.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.cst_modified
     *
     * @param cstModified the value for final_settlement_item.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_settlement_item.is_del
     *
     * @return the value of final_settlement_item.is_del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_settlement_item.is_del
     *
     * @param del the value for final_settlement_item.is_del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_settlement_item
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", projectId=").append(projectId);
        sb.append(", subprojectName=").append(subprojectName);
        sb.append(", submitMoney=").append(submitMoney);
        sb.append(", checkedMoney=").append(checkedMoney);
        sb.append(", increasedMoney=").append(increasedMoney);
        sb.append(", decreasedMoney=").append(decreasedMoney);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", del=").append(del);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}