package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table internal_settlement
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class InternalSettlement implements Serializable {
    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   工期目标完成情况
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * Database Column Remarks:
     *   质量目标完成情况
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.quality
     *
     * @mbg.generated
     */
    private String quality;

    /**
     * Database Column Remarks:
     *   安全与文明施工目标完成情况
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.safety
     *
     * @mbg.generated
     */
    private String safety;

    /**
     * Database Column Remarks:
     *   成本目标（单位：元）完成情况
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.cost
     *
     * @mbg.generated
     */
    private BigDecimal cost;

    /**
     * Database Column Remarks:
     *   内部结算金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.internal_cost
     *
     * @mbg.generated
     */
    private BigDecimal internalCost;

    /**
     * Database Column Remarks:
     *   额外奖励金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.extra_award
     *
     * @mbg.generated
     */
    private BigDecimal extraAward;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_settlement.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table internal_settlement
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.project_id
     *
     * @return the value of internal_settlement.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.project_id
     *
     * @param projectId the value for internal_settlement.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.company_id
     *
     * @return the value of internal_settlement.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.company_id
     *
     * @param companyId the value for internal_settlement.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.duration
     *
     * @return the value of internal_settlement.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.duration
     *
     * @param duration the value for internal_settlement.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.quality
     *
     * @return the value of internal_settlement.quality
     *
     * @mbg.generated
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.quality
     *
     * @param quality the value for internal_settlement.quality
     *
     * @mbg.generated
     */
    public void setQuality(String quality) {
        this.quality = quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.safety
     *
     * @return the value of internal_settlement.safety
     *
     * @mbg.generated
     */
    public String getSafety() {
        return safety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.safety
     *
     * @param safety the value for internal_settlement.safety
     *
     * @mbg.generated
     */
    public void setSafety(String safety) {
        this.safety = safety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.cost
     *
     * @return the value of internal_settlement.cost
     *
     * @mbg.generated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.cost
     *
     * @param cost the value for internal_settlement.cost
     *
     * @mbg.generated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.internal_cost
     *
     * @return the value of internal_settlement.internal_cost
     *
     * @mbg.generated
     */
    public BigDecimal getInternalCost() {
        return internalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.internal_cost
     *
     * @param internalCost the value for internal_settlement.internal_cost
     *
     * @mbg.generated
     */
    public void setInternalCost(BigDecimal internalCost) {
        this.internalCost = internalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.extra_award
     *
     * @return the value of internal_settlement.extra_award
     *
     * @mbg.generated
     */
    public BigDecimal getExtraAward() {
        return extraAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.extra_award
     *
     * @param extraAward the value for internal_settlement.extra_award
     *
     * @mbg.generated
     */
    public void setExtraAward(BigDecimal extraAward) {
        this.extraAward = extraAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.cst_create
     *
     * @return the value of internal_settlement.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.cst_create
     *
     * @param cstCreate the value for internal_settlement.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_settlement.cst_modified
     *
     * @return the value of internal_settlement.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_settlement.cst_modified
     *
     * @param cstModified the value for internal_settlement.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_settlement
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectId=").append(projectId);
        sb.append(", companyId=").append(companyId);
        sb.append(", duration=").append(duration);
        sb.append(", quality=").append(quality);
        sb.append(", safety=").append(safety);
        sb.append(", cost=").append(cost);
        sb.append(", internalCost=").append(internalCost);
        sb.append(", extraAward=").append(extraAward);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}