package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table material_headquarters_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MaterialHeadquartersOrder implements Serializable {
	/** 类型-入库*/
	public static final String TYPE_IMPORT = "IMPORT";
	/** 类型-出库*/
	public static final String TYPE_EXPORT = "EXPORT";
    /**
     * Database Column Remarks:
     *   总部材料订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.id
     *
     * @mbg.generated
     */
    private BigInteger id;
    private BigInteger targetProjectId;
    private List<MaterialHeadquartersOrderDetail> materialHeadquartersOrderDetails;
    
    public List<MaterialHeadquartersOrderDetail> getMaterialHeadquartersOrderDetails() {
		return materialHeadquartersOrderDetails;
	}

	public void setMaterialHeadquartersOrderDetails(List<MaterialHeadquartersOrderDetail> materialHeadquartersOrderDetails) {
		this.materialHeadquartersOrderDetails = materialHeadquartersOrderDetails;
	}

	public BigInteger getTargetProjectId() {
		return targetProjectId;
	}

	public void setTargetProjectId(BigInteger targetProjectId) {
		this.targetProjectId = targetProjectId;
	}

	/**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   出入库员工ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.staff_id
     *
     * @mbg.generated
     */
    private BigInteger staffId;

    /**
     * Database Column Remarks:
     *   出入库员工名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.staff_name
     *
     * @mbg.generated
     */
    private String staffName;

    /**
     * Database Column Remarks:
     *   批次号（系统生成，以HQB开头）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.batch_no
     *
     * @mbg.generated
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     * Database Column Remarks:
     *   类型（出库：OUT，入库：IN）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order.is_del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_headquarters_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.id
     *
     * @return the value of material_headquarters_order.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.id
     *
     * @param id the value for material_headquarters_order.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.company_id
     *
     * @return the value of material_headquarters_order.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.company_id
     *
     * @param companyId the value for material_headquarters_order.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.staff_id
     *
     * @return the value of material_headquarters_order.staff_id
     *
     * @mbg.generated
     */
    public BigInteger getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.staff_id
     *
     * @param staffId the value for material_headquarters_order.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(BigInteger staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.staff_name
     *
     * @return the value of material_headquarters_order.staff_name
     *
     * @mbg.generated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.staff_name
     *
     * @param staffName the value for material_headquarters_order.staff_name
     *
     * @mbg.generated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.batch_no
     *
     * @return the value of material_headquarters_order.batch_no
     *
     * @mbg.generated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.batch_no
     *
     * @param batchNo the value for material_headquarters_order.batch_no
     *
     * @mbg.generated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.money
     *
     * @return the value of material_headquarters_order.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.money
     *
     * @param money the value for material_headquarters_order.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.type
     *
     * @return the value of material_headquarters_order.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.type
     *
     * @param type the value for material_headquarters_order.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.cst_create
     *
     * @return the value of material_headquarters_order.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.cst_create
     *
     * @param cstCreate the value for material_headquarters_order.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.cst_modified
     *
     * @return the value of material_headquarters_order.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.cst_modified
     *
     * @param cstModified the value for material_headquarters_order.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order.is_del
     *
     * @return the value of material_headquarters_order.is_del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order.is_del
     *
     * @param del the value for material_headquarters_order.is_del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", targetProjectId=").append(targetProjectId);
        sb.append(", companyId=").append(companyId);
        sb.append(", staffId=").append(staffId);
        sb.append(", staffName=").append(staffName);
        sb.append(", batchNo=").append(batchNo);
        sb.append(", money=").append(money);
        sb.append(", type=").append(type);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", del=").append(del);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}