package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table material_headquarters_order_detail
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MaterialHeadquartersOrderDetail implements Serializable {
    /**
     * Database Column Remarks:
     *   总部材料订单详情ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   总部材料订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.material_headquarters_order_id
     *
     * @mbg.generated
     */
    private BigInteger materialHeadquartersOrderId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     * Database Column Remarks:
     *   规格型号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     * Database Column Remarks:
     *   计量单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters_order_detail.is_del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_headquarters_order_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.id
     *
     * @return the value of material_headquarters_order_detail.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.id
     *
     * @param id the value for material_headquarters_order_detail.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.company_id
     *
     * @return the value of material_headquarters_order_detail.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.company_id
     *
     * @param companyId the value for material_headquarters_order_detail.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.material_headquarters_order_id
     *
     * @return the value of material_headquarters_order_detail.material_headquarters_order_id
     *
     * @mbg.generated
     */
    public BigInteger getMaterialHeadquartersOrderId() {
        return materialHeadquartersOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.material_headquarters_order_id
     *
     * @param materialHeadquartersOrderId the value for material_headquarters_order_detail.material_headquarters_order_id
     *
     * @mbg.generated
     */
    public void setMaterialHeadquartersOrderId(BigInteger materialHeadquartersOrderId) {
        this.materialHeadquartersOrderId = materialHeadquartersOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.name
     *
     * @return the value of material_headquarters_order_detail.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.name
     *
     * @param name the value for material_headquarters_order_detail.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.num
     *
     * @return the value of material_headquarters_order_detail.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.num
     *
     * @param num the value for material_headquarters_order_detail.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.model
     *
     * @return the value of material_headquarters_order_detail.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.model
     *
     * @param model the value for material_headquarters_order_detail.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.unit
     *
     * @return the value of material_headquarters_order_detail.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.unit
     *
     * @param unit the value for material_headquarters_order_detail.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.amount
     *
     * @return the value of material_headquarters_order_detail.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.amount
     *
     * @param amount the value for material_headquarters_order_detail.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.price
     *
     * @return the value of material_headquarters_order_detail.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.price
     *
     * @param price the value for material_headquarters_order_detail.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.money
     *
     * @return the value of material_headquarters_order_detail.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.money
     *
     * @param money the value for material_headquarters_order_detail.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.cst_create
     *
     * @return the value of material_headquarters_order_detail.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.cst_create
     *
     * @param cstCreate the value for material_headquarters_order_detail.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.cst_modified
     *
     * @return the value of material_headquarters_order_detail.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.cst_modified
     *
     * @param cstModified the value for material_headquarters_order_detail.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters_order_detail.is_del
     *
     * @return the value of material_headquarters_order_detail.is_del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters_order_detail.is_del
     *
     * @param del the value for material_headquarters_order_detail.is_del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters_order_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", materialHeadquartersOrderId=").append(materialHeadquartersOrderId);
        sb.append(", name=").append(name);
        sb.append(", num=").append(num);
        sb.append(", model=").append(model);
        sb.append(", unit=").append(unit);
        sb.append(", amount=").append(amount);
        sb.append(", price=").append(price);
        sb.append(", money=").append(money);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", del=").append(del);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}