package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table material_headquarters
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MaterialHeadquarters implements Serializable {
    /**
     * Database Column Remarks:
     *   总部材料ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     * Database Column Remarks:
     *   规格型号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     * Database Column Remarks:
     *   计量单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * Database Column Remarks:
     *   数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   冻结的数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.amount_freeze
     *
     * @mbg.generated
     */
    private BigDecimal amountFreeze;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_headquarters.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material_headquarters
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.id
     *
     * @return the value of material_headquarters.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.id
     *
     * @param id the value for material_headquarters.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.company_id
     *
     * @return the value of material_headquarters.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.company_id
     *
     * @param companyId the value for material_headquarters.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.name
     *
     * @return the value of material_headquarters.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.name
     *
     * @param name the value for material_headquarters.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.num
     *
     * @return the value of material_headquarters.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.num
     *
     * @param num the value for material_headquarters.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.model
     *
     * @return the value of material_headquarters.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.model
     *
     * @param model the value for material_headquarters.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.unit
     *
     * @return the value of material_headquarters.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.unit
     *
     * @param unit the value for material_headquarters.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.amount
     *
     * @return the value of material_headquarters.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.amount
     *
     * @param amount the value for material_headquarters.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.amount_freeze
     *
     * @return the value of material_headquarters.amount_freeze
     *
     * @mbg.generated
     */
    public BigDecimal getAmountFreeze() {
        return amountFreeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.amount_freeze
     *
     * @param amountFreeze the value for material_headquarters.amount_freeze
     *
     * @mbg.generated
     */
    public void setAmountFreeze(BigDecimal amountFreeze) {
        this.amountFreeze = amountFreeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.cst_create
     *
     * @return the value of material_headquarters.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.cst_create
     *
     * @param cstCreate the value for material_headquarters.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_headquarters.cst_modified
     *
     * @return the value of material_headquarters.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_headquarters.cst_modified
     *
     * @param cstModified the value for material_headquarters.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_headquarters
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", name=").append(name);
        sb.append(", num=").append(num);
        sb.append(", model=").append(model);
        sb.append(", unit=").append(unit);
        sb.append(", amount=").append(amount);
        sb.append(", amountFreeze=").append(amountFreeze);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}