package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table product_capacity_item
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductCapacityItem implements Serializable {
	/**
	 * Database Column Remarks: 生产管理ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.id
	 *
	 * @mbg.generated
	 */
	private BigInteger id;

	/**
	 * Database Column Remarks: 企业ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.company_id
	 *
	 * @mbg.generated
	 */
	private BigInteger companyId;

	/**
	 * Database Column Remarks: 项目ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.project_id
	 *
	 * @mbg.generated
	 */
	private BigInteger projectId;

	/**
	 * Database Column Remarks: 年份
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.year
	 *
	 * @mbg.generated
	 */
	private Integer year;

	/**
	 * Database Column Remarks: 月份
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.month
	 *
	 * @mbg.generated
	 */
	private Integer month;

	/**
	 * Database Column Remarks: 预期进度（单位：天）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.expected_value
	 *
	 * @mbg.generated
	 */
	private String expectedState;

	/**
	 * Database Column Remarks: 预期进度（单位：天）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.actual_value
	 *
	 * @mbg.generated
	 */
	private String actualState;

	/**
	 * Database Column Remarks: 核定进度（单位：天）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.checked_value
	 *
	 * @mbg.generated
	 */
	private String checkedState;

	/**
	 * Database Column Remarks: 是否核定标识
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.is_checked
	 *
	 * @mbg.generated
	 */
	private Boolean checked;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.staff_id
	 *
	 * @mbg.generated
	 */
	private BigInteger staffId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.staff_name
	 *
	 * @mbg.generated
	 */
	private String staffName;

	/**
	 * Database Column Remarks: 修改时间
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.cst_modified
	 *
	 * @mbg.generated
	 */
	private Date cstModified;

	/**
	 * Database Column Remarks: 创建时间
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column product_capacity_item.cst_create
	 *
	 * @mbg.generated
	 */
	private Date cstCreate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product_capacity_item
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.id
	 *
	 * @return the value of product_capacity_item.id
	 *
	 * @mbg.generated
	 */
	public BigInteger getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.id
	 *
	 * @param id
	 *            the value for product_capacity_item.id
	 *
	 * @mbg.generated
	 */
	public void setId(BigInteger id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.company_id
	 *
	 * @return the value of product_capacity_item.company_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.company_id
	 *
	 * @param companyId
	 *            the value for product_capacity_item.company_id
	 *
	 * @mbg.generated
	 */
	public void setCompanyId(BigInteger companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.project_id
	 *
	 * @return the value of product_capacity_item.project_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.project_id
	 *
	 * @param projectId
	 *            the value for product_capacity_item.project_id
	 *
	 * @mbg.generated
	 */
	public void setProjectId(BigInteger projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.year
	 *
	 * @return the value of product_capacity_item.year
	 *
	 * @mbg.generated
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.year
	 *
	 * @param year
	 *            the value for product_capacity_item.year
	 *
	 * @mbg.generated
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.month
	 *
	 * @return the value of product_capacity_item.month
	 *
	 * @mbg.generated
	 */
	public Integer getMonth() {
		return month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.month
	 *
	 * @param month
	 *            the value for product_capacity_item.month
	 *
	 * @mbg.generated
	 */
	public void setMonth(Integer month) {
		this.month = month;
	}

	public String getExpectedState() {
		return expectedState;
	}

	public void setExpectedState(String expectedState) {
		this.expectedState = expectedState;
	}

	public String getActualState() {
		return actualState;
	}

	public void setActualState(String actualState) {
		this.actualState = actualState;
	}

	public String getCheckedState() {
		return checkedState;
	}

	public void setCheckedState(String checkedState) {
		this.checkedState = checkedState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.is_checked
	 *
	 * @return the value of product_capacity_item.is_checked
	 *
	 * @mbg.generated
	 */
	public Boolean getChecked() {
		return checked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.is_checked
	 *
	 * @param checked
	 *            the value for product_capacity_item.is_checked
	 *
	 * @mbg.generated
	 */
	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.staff_id
	 *
	 * @return the value of product_capacity_item.staff_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.staff_id
	 *
	 * @param staffId
	 *            the value for product_capacity_item.staff_id
	 *
	 * @mbg.generated
	 */
	public void setStaffId(BigInteger staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.staff_name
	 *
	 * @return the value of product_capacity_item.staff_name
	 *
	 * @mbg.generated
	 */
	public String getStaffName() {
		return staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.staff_name
	 *
	 * @param staffName
	 *            the value for product_capacity_item.staff_name
	 *
	 * @mbg.generated
	 */
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.cst_modified
	 *
	 * @return the value of product_capacity_item.cst_modified
	 *
	 * @mbg.generated
	 */
	public Date getCstModified() {
		return cstModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.cst_modified
	 *
	 * @param cstModified
	 *            the value for product_capacity_item.cst_modified
	 *
	 * @mbg.generated
	 */
	public void setCstModified(Date cstModified) {
		this.cstModified = cstModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column product_capacity_item.cst_create
	 *
	 * @return the value of product_capacity_item.cst_create
	 *
	 * @mbg.generated
	 */
	public Date getCstCreate() {
		return cstCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column product_capacity_item.cst_create
	 *
	 * @param cstCreate
	 *            the value for product_capacity_item.cst_create
	 *
	 * @mbg.generated
	 */
	public void setCstCreate(Date cstCreate) {
		this.cstCreate = cstCreate;
	}

	@Override
	public String toString() {
		return "ProductCapacityItem [id=" + id + ", companyId=" + companyId + ", projectId=" + projectId + ", year="
				+ year + ", month=" + month + ", expectedState=" + expectedState + ", actualState=" + actualState
				+ ", checkedState=" + checkedState + ", checked=" + checked + ", staffId=" + staffId + ", staffName="
				+ staffName + ", cstModified=" + cstModified + ", cstCreate=" + cstCreate + "]";
	}

}