package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project_team
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProjectTeam implements Serializable {
    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   企业员工ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team.staff_id
     *
     * @mbg.generated
     */
    private BigInteger staffId;

    /**
     * Database Column Remarks:
     *   项目角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_team.team_role_id
     *
     * @mbg.generated
     */
    private BigInteger teamRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_team
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team.project_id
     *
     * @return the value of project_team.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team.project_id
     *
     * @param projectId the value for project_team.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team.staff_id
     *
     * @return the value of project_team.staff_id
     *
     * @mbg.generated
     */
    public BigInteger getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team.staff_id
     *
     * @param staffId the value for project_team.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(BigInteger staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_team.team_role_id
     *
     * @return the value of project_team.team_role_id
     *
     * @mbg.generated
     */
    public BigInteger getTeamRoleId() {
        return teamRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_team.team_role_id
     *
     * @param teamRoleId the value for project_team.team_role_id
     *
     * @mbg.generated
     */
    public void setTeamRoleId(BigInteger teamRoleId) {
        this.teamRoleId = teamRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectId=").append(projectId);
        sb.append(", staffId=").append(staffId);
        sb.append(", teamRoleId=").append(teamRoleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}