package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table project
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Project implements Serializable {
	/** 项目状态-进行中 */
	public static final String FILE_STATUS_GOING = "GOING";
	/** 项目状态-归档 */
	public static final String FILE_STATUS_ARCHIVED = "ARCHIVED";
	/** 项目解体状态-进行中 */
	public static final String COLLAPSE_STATUS_GOING = "GOING";
	/** 项目解体状态-已解体 */
	public static final String COLLAPSE_STATUS_COLLAPSED = "COLLAPSED";
	public static final List<String> STATUS_LIST = Arrays
			.asList(new String[] { FILE_STATUS_GOING, FILE_STATUS_ARCHIVED });
    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     * Database Column Remarks:
     *   项目名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   建设方名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.constructer_name
     *
     * @mbg.generated
     */
    private String constructerName;

    /**
     * Database Column Remarks:
     *   设计方名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.designer_name
     *
     * @mbg.generated
     */
    private String designerName;

    /**
     * Database Column Remarks:
     *   监理方名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.superviser_name
     *
     * @mbg.generated
     */
    private String superviserName;

    /**
     * Database Column Remarks:
     *   工程地点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   工程类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   工程规模
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.scale
     *
     * @mbg.generated
     */
    private String scale;

    /**
     * Database Column Remarks:
     *   中标工期（单元：天）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.bid_duration
     *
     * @mbg.generated
     */
    private Integer bidDuration;

    /**
     * Database Column Remarks:
     *   项目状态（进行中:GOING，已归档：ARCHIVED）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.file_status
     *
     * @mbg.generated
     */
    private String fileStatus;

    /**
     * Database Column Remarks:
     *   解体状态（运行中：GOING，已解体：COLLAPSED）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.collapse_status
     *
     * @mbg.generated
     */
    private String collapseStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   中标价（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.bid_price
     *
     * @mbg.generated
     */
    private BigDecimal bidPrice;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.is_del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.company_id
     *
     * @return the value of project.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.company_id
     *
     * @param companyId the value for project.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.num
     *
     * @return the value of project.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.num
     *
     * @param num the value for project.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.constructer_name
     *
     * @return the value of project.constructer_name
     *
     * @mbg.generated
     */
    public String getConstructerName() {
        return constructerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.constructer_name
     *
     * @param constructerName the value for project.constructer_name
     *
     * @mbg.generated
     */
    public void setConstructerName(String constructerName) {
        this.constructerName = constructerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.designer_name
     *
     * @return the value of project.designer_name
     *
     * @mbg.generated
     */
    public String getDesignerName() {
        return designerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.designer_name
     *
     * @param designerName the value for project.designer_name
     *
     * @mbg.generated
     */
    public void setDesignerName(String designerName) {
        this.designerName = designerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.superviser_name
     *
     * @return the value of project.superviser_name
     *
     * @mbg.generated
     */
    public String getSuperviserName() {
        return superviserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.superviser_name
     *
     * @param superviserName the value for project.superviser_name
     *
     * @mbg.generated
     */
    public void setSuperviserName(String superviserName) {
        this.superviserName = superviserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.address
     *
     * @return the value of project.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.address
     *
     * @param address the value for project.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.type
     *
     * @return the value of project.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.type
     *
     * @param type the value for project.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.scale
     *
     * @return the value of project.scale
     *
     * @mbg.generated
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.scale
     *
     * @param scale the value for project.scale
     *
     * @mbg.generated
     */
    public void setScale(String scale) {
        this.scale = scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.bid_duration
     *
     * @return the value of project.bid_duration
     *
     * @mbg.generated
     */
    public Integer getBidDuration() {
        return bidDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.bid_duration
     *
     * @param bidDuration the value for project.bid_duration
     *
     * @mbg.generated
     */
    public void setBidDuration(Integer bidDuration) {
        this.bidDuration = bidDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.file_status
     *
     * @return the value of project.file_status
     *
     * @mbg.generated
     */
    public String getFileStatus() {
        return fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.file_status
     *
     * @param fileStatus the value for project.file_status
     *
     * @mbg.generated
     */
    public void setFileStatus(String fileStatus) {
        this.fileStatus = fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.collapse_status
     *
     * @return the value of project.collapse_status
     *
     * @mbg.generated
     */
    public String getCollapseStatus() {
        return collapseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.collapse_status
     *
     * @param collapseStatus the value for project.collapse_status
     *
     * @mbg.generated
     */
    public void setCollapseStatus(String collapseStatus) {
        this.collapseStatus = collapseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.cst_create
     *
     * @return the value of project.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.cst_create
     *
     * @param cstCreate the value for project.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.cst_modified
     *
     * @return the value of project.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.cst_modified
     *
     * @param cstModified the value for project.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.bid_price
     *
     * @return the value of project.bid_price
     *
     * @mbg.generated
     */
    public BigDecimal getBidPrice() {
        return bidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.bid_price
     *
     * @param bidPrice the value for project.bid_price
     *
     * @mbg.generated
     */
    public void setBidPrice(BigDecimal bidPrice) {
        this.bidPrice = bidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.memo
     *
     * @return the value of project.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.memo
     *
     * @param memo the value for project.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.is_del
     *
     * @return the value of project.is_del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.is_del
     *
     * @param del the value for project.is_del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

	@Override
	public String toString() {
		return "Project [id=" + id + ", companyId=" + companyId + ", num=" + num + ", name=" + name
				+ ", constructerName=" + constructerName + ", designerName=" + designerName + ", superviserName="
				+ superviserName + ", address=" + address + ", type=" + type + ", scale=" + scale + ", bidDuration="
				+ bidDuration + ", fileStatus=" + fileStatus + ", collapseStatus="
				+ collapseStatus + ", cstCreate=" + cstCreate + ", cstModified=" + cstModified + ", bidPrice="
				+ bidPrice + ", memo=" + memo + ", del=" + del + ", hashCode()=" + hashCode() + "]";
	}
    
    
}