package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table project_application
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProjectApplication implements Serializable {
	/** 类型-项目经理 */
	public static final String TYPE_PROJECT_MANAGER = "PROJECT_MANAGER";
	/** 类型-技术负责人 */
	public static final String TYPE_TECHNICAL_DIRECTOR = "TECHNICAL_DIRECTOR";
	/** 类型-施工员 */
	public static final String TYPE_CONSTRUCTION_WORKER = "CONSTRUCTION_WORKER";
	/** 类型-质量员 */
	public static final String TYPE_QUALITY_WORKER = "QUALITY_WORKER";
	/** 类型-安全员 */
	public static final String TYPE_SAFETY_WORKER = "SAFETY_WORKER";
	/** 类型-预算员 */
	public static final String TYPE_BUDGETER = "BUDGETER";
	/** 类型-材料员 */
	public static final String TYPE_MATERIALMAN = "MATERIALMAN";
	/** 类型-机械员 */
	public static final String TYPE_MACHINIST = "MACHINIST";
	/** 类型-劳务员 */
	public static final String TYPE_LABOR_WORKER = "LABOR_WORKER";
	/** 类型-资料员 */
	public static final String TYPE_DATA_PROCESSOR = "DATA_PROCESSOR";
	public static final List<String> TYPE_LIST = Arrays.asList(new String[] { TYPE_PROJECT_MANAGER, TYPE_TECHNICAL_DIRECTOR, TYPE_CONSTRUCTION_WORKER, TYPE_QUALITY_WORKER, TYPE_SAFETY_WORKER,
			TYPE_BUDGETER, TYPE_MATERIALMAN, TYPE_MACHINIST, TYPE_LABOR_WORKER, TYPE_DATA_PROCESSOR });
	/**
	 * Database Column Remarks: 项目ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column project_application.project_id
	 *
	 * @mbg.generated
	 */
	private BigInteger projectId;

	/**
	 * Database Column Remarks: 企业人员ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column project_application.staff_id
	 *
	 * @mbg.generated
	 */
	private BigInteger staffId;

	/**
	 * Database Column Remarks: 报建人员类型
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column project_application.type
	 *
	 * @mbg.generated
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table project_application
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column project_application.project_id
	 *
	 * @return the value of project_application.project_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column project_application.project_id
	 *
	 * @param projectId
	 *            the value for project_application.project_id
	 *
	 * @mbg.generated
	 */
	public void setProjectId(BigInteger projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column project_application.staff_id
	 *
	 * @return the value of project_application.staff_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column project_application.staff_id
	 *
	 * @param staffId
	 *            the value for project_application.staff_id
	 *
	 * @mbg.generated
	 */
	public void setStaffId(BigInteger staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column project_application.type
	 *
	 * @return the value of project_application.type
	 *
	 * @mbg.generated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column project_application.type
	 *
	 * @param type
	 *            the value for project_application.type
	 *
	 * @mbg.generated
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table project_application
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", projectId=").append(projectId);
		sb.append(", staffId=").append(staffId);
		sb.append(", type=").append(type);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}