package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_has_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleHasPermission implements Serializable {
    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_permission.role_id
     *
     * @mbg.generated
     */
    private BigInteger roleId;

    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_permission.permission_id
     *
     * @mbg.generated
     */
    private BigInteger permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_has_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_permission.role_id
     *
     * @return the value of role_has_permission.role_id
     *
     * @mbg.generated
     */
    public BigInteger getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_permission.role_id
     *
     * @param roleId the value for role_has_permission.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(BigInteger roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_permission.permission_id
     *
     * @return the value of role_has_permission.permission_id
     *
     * @mbg.generated
     */
    public BigInteger getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_permission.permission_id
     *
     * @param permissionId the value for role_has_permission.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(BigInteger permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_permission
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}