package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table staff_has_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class StaffHasRole implements Serializable {
    /**
     * Database Column Remarks:
     *   企业员工ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_has_role.staff_id
     *
     * @mbg.generated
     */
    private BigInteger staffId;

    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_has_role.role_id
     *
     * @mbg.generated
     */
    private BigInteger roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff_has_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_has_role.staff_id
     *
     * @return the value of staff_has_role.staff_id
     *
     * @mbg.generated
     */
    public BigInteger getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_has_role.staff_id
     *
     * @param staffId the value for staff_has_role.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(BigInteger staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_has_role.role_id
     *
     * @return the value of staff_has_role.role_id
     *
     * @mbg.generated
     */
    public BigInteger getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_has_role.role_id
     *
     * @param roleId the value for staff_has_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(BigInteger roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_has_role
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", staffId=").append(staffId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public StaffHasRole(BigInteger staffId, BigInteger roleId) {
		super();
		this.staffId = staffId;
		this.roleId = roleId;
	}

	public StaffHasRole() {
		super();
		// TODO Auto-generated constructor stub
	}
    
    
}