package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table staff
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Staff implements Serializable {
	public static final String SEX_MALE = "MALE";
	public static final String SEX_FEMALE = "FEMALE";
	/** 角色列表 */
	private List<Role> roles;
    /**
     * Database Column Remarks:
     *   企业员工ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   性别（MALE/FEMALE）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   工号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.job_no
     *
     * @mbg.generated
     */
    private String jobNo;

    /**
     * Database Column Remarks:
     *   籍贯
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.native_place
     *
     * @mbg.generated
     */
    private String nativePlace;

    /**
     * Database Column Remarks:
     *   联系方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   身份证号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id_card_no
     *
     * @mbg.generated
     */
    private String idCardNo;

    /**
     * Database Column Remarks:
     *   家庭住址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   入职时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.entry_date
     *
     * @mbg.generated
     */
    private Date entryDate;

    /**
     * Database Column Remarks:
     *   职业经历
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.career
     *
     * @mbg.generated
     */
    private String career;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   盐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.is_del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id
     *
     * @return the value of staff.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id
     *
     * @param id the value for staff.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.company_id
     *
     * @return the value of staff.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.company_id
     *
     * @param companyId the value for staff.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.name
     *
     * @return the value of staff.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.name
     *
     * @param name the value for staff.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.sex
     *
     * @return the value of staff.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.sex
     *
     * @param sex the value for staff.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.job_no
     *
     * @return the value of staff.job_no
     *
     * @mbg.generated
     */
    public String getJobNo() {
        return jobNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.job_no
     *
     * @param jobNo the value for staff.job_no
     *
     * @mbg.generated
     */
    public void setJobNo(String jobNo) {
        this.jobNo = jobNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.native_place
     *
     * @return the value of staff.native_place
     *
     * @mbg.generated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.native_place
     *
     * @param nativePlace the value for staff.native_place
     *
     * @mbg.generated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.phone
     *
     * @return the value of staff.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.phone
     *
     * @param phone the value for staff.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id_card_no
     *
     * @return the value of staff.id_card_no
     *
     * @mbg.generated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id_card_no
     *
     * @param idCardNo the value for staff.id_card_no
     *
     * @mbg.generated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.address
     *
     * @return the value of staff.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.address
     *
     * @param address the value for staff.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.entry_date
     *
     * @return the value of staff.entry_date
     *
     * @mbg.generated
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.entry_date
     *
     * @param entryDate the value for staff.entry_date
     *
     * @mbg.generated
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.career
     *
     * @return the value of staff.career
     *
     * @mbg.generated
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.career
     *
     * @param career the value for staff.career
     *
     * @mbg.generated
     */
    public void setCareer(String career) {
        this.career = career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.birthday
     *
     * @return the value of staff.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.birthday
     *
     * @param birthday the value for staff.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.salt
     *
     * @return the value of staff.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.salt
     *
     * @param salt the value for staff.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.password
     *
     * @return the value of staff.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.password
     *
     * @param password the value for staff.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.cst_create
     *
     * @return the value of staff.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.cst_create
     *
     * @param cstCreate the value for staff.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.cst_modified
     *
     * @return the value of staff.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.cst_modified
     *
     * @param cstModified the value for staff.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.memo
     *
     * @return the value of staff.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.memo
     *
     * @param memo the value for staff.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.is_del
     *
     * @return the value of staff.is_del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.is_del
     *
     * @param del the value for staff.is_del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	@Override
	public String toString() {
		return "Staff [roles=" + roles + ", id=" + id + ", companyId=" + companyId + ", name=" + name + ", sex=" + sex
				+ ", jobNo=" + jobNo + ", nativePlace=" + nativePlace + ", phone=" + phone + ", idCardNo=" + idCardNo
				+ ", address=" + address + ", entryDate=" + entryDate + ", career=" + career + ", birthday=" + birthday
				+ ", salt=" + salt + ", password=" + password + ", cstCreate=" + cstCreate + ", cstModified="
				+ cstModified + ", memo=" + memo + ", del=" + del + ", hashCode()=" + hashCode() + "]";
	}
    
    
}