package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table subcontractor_has_subcontractor_qualification
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SubcontractorHasSubcontractorQualification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subcontractor_has_subcontractor_qualification.subcontractor_id
     *
     * @mbg.generated
     */
    private BigInteger subcontractorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subcontractor_has_subcontractor_qualification.subcontractor_qualification_id
     *
     * @mbg.generated
     */
    private BigInteger subcontractorQualificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subcontractor_has_subcontractor_qualification
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subcontractor_has_subcontractor_qualification.subcontractor_id
     *
     * @return the value of subcontractor_has_subcontractor_qualification.subcontractor_id
     *
     * @mbg.generated
     */
    public BigInteger getSubcontractorId() {
        return subcontractorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subcontractor_has_subcontractor_qualification.subcontractor_id
     *
     * @param subcontractorId the value for subcontractor_has_subcontractor_qualification.subcontractor_id
     *
     * @mbg.generated
     */
    public void setSubcontractorId(BigInteger subcontractorId) {
        this.subcontractorId = subcontractorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subcontractor_has_subcontractor_qualification.subcontractor_qualification_id
     *
     * @return the value of subcontractor_has_subcontractor_qualification.subcontractor_qualification_id
     *
     * @mbg.generated
     */
    public BigInteger getSubcontractorQualificationId() {
        return subcontractorQualificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subcontractor_has_subcontractor_qualification.subcontractor_qualification_id
     *
     * @param subcontractorQualificationId the value for subcontractor_has_subcontractor_qualification.subcontractor_qualification_id
     *
     * @mbg.generated
     */
    public void setSubcontractorQualificationId(BigInteger subcontractorQualificationId) {
        this.subcontractorQualificationId = subcontractorQualificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcontractor_has_subcontractor_qualification
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", subcontractorId=").append(subcontractorId);
        sb.append(", subcontractorQualificationId=").append(subcontractorQualificationId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public SubcontractorHasSubcontractorQualification(BigInteger subcontractorId,
			BigInteger subcontractorQualificationId) {
		super();
		this.subcontractorId = subcontractorId;
		this.subcontractorQualificationId = subcontractorQualificationId;
	}

	public SubcontractorHasSubcontractorQualification() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}