package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table supplier_has_supplier_qualification
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SupplierHasSupplierQualification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_has_supplier_qualification.supplier_id
     *
     * @mbg.generated
     */
    private BigInteger supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_has_supplier_qualification.supplier_qualification_id
     *
     * @mbg.generated
     */
    private BigInteger supplierQualificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier_has_supplier_qualification
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_has_supplier_qualification.supplier_id
     *
     * @return the value of supplier_has_supplier_qualification.supplier_id
     *
     * @mbg.generated
     */
    public BigInteger getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_has_supplier_qualification.supplier_id
     *
     * @param supplierId the value for supplier_has_supplier_qualification.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(BigInteger supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_has_supplier_qualification.supplier_qualification_id
     *
     * @return the value of supplier_has_supplier_qualification.supplier_qualification_id
     *
     * @mbg.generated
     */
    public BigInteger getSupplierQualificationId() {
        return supplierQualificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_has_supplier_qualification.supplier_qualification_id
     *
     * @param supplierQualificationId the value for supplier_has_supplier_qualification.supplier_qualification_id
     *
     * @mbg.generated
     */
    public void setSupplierQualificationId(BigInteger supplierQualificationId) {
        this.supplierQualificationId = supplierQualificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_has_supplier_qualification
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", supplierId=").append(supplierId);
        sb.append(", supplierQualificationId=").append(supplierQualificationId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public SupplierHasSupplierQualification(BigInteger supplierId, BigInteger supplierQualificationId) {
		super();
		this.supplierId = supplierId;
		this.supplierQualificationId = supplierQualificationId;
	}

	public SupplierHasSupplierQualification() {
		super();
		// TODO Auto-generated constructor stub
	}
    
    
}