package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table target
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Target implements Serializable {
    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   工期目标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * Database Column Remarks:
     *   开工时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * Database Column Remarks:
     *   完工时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     * Database Column Remarks:
     *   质量目标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.quality
     *
     * @mbg.generated
     */
    private String quality;

    /**
     * Database Column Remarks:
     *   安全与文明施工目标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.safety
     *
     * @mbg.generated
     */
    private String safety;

    /**
     * Database Column Remarks:
     *   成本目标（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.cost
     *
     * @mbg.generated
     */
    private BigDecimal cost;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table target
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.project_id
     *
     * @return the value of target.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.project_id
     *
     * @param projectId the value for target.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.company_id
     *
     * @return the value of target.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.company_id
     *
     * @param companyId the value for target.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.duration
     *
     * @return the value of target.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.duration
     *
     * @param duration the value for target.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.start_date
     *
     * @return the value of target.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.start_date
     *
     * @param startDate the value for target.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.end_date
     *
     * @return the value of target.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.end_date
     *
     * @param endDate the value for target.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.quality
     *
     * @return the value of target.quality
     *
     * @mbg.generated
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.quality
     *
     * @param quality the value for target.quality
     *
     * @mbg.generated
     */
    public void setQuality(String quality) {
        this.quality = quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.safety
     *
     * @return the value of target.safety
     *
     * @mbg.generated
     */
    public String getSafety() {
        return safety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.safety
     *
     * @param safety the value for target.safety
     *
     * @mbg.generated
     */
    public void setSafety(String safety) {
        this.safety = safety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.cost
     *
     * @return the value of target.cost
     *
     * @mbg.generated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.cost
     *
     * @param cost the value for target.cost
     *
     * @mbg.generated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.memo
     *
     * @return the value of target.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.memo
     *
     * @param memo the value for target.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.cst_create
     *
     * @return the value of target.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.cst_create
     *
     * @param cstCreate the value for target.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.cst_modified
     *
     * @return the value of target.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.cst_modified
     *
     * @param cstModified the value for target.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectId=").append(projectId);
        sb.append(", companyId=").append(companyId);
        sb.append(", duration=").append(duration);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", quality=").append(quality);
        sb.append(", safety=").append(safety);
        sb.append(", cost=").append(cost);
        sb.append(", memo=").append(memo);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}