package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TeamRole implements Serializable {
	/** 类型-项目经理 */
	public static final String TYPE_PROJECT_MANAGER = "PROJECT_MANAGER";
	/** 类型-技术负责人 */
	public static final String TYPE_TECHNICAL_DIRECTOR = "TECHNICAL_DIRECTOR";
	/** 类型-施工员 */
	public static final String TYPE_CONSTRUCTION_WORKER = "CONSTRUCTION_WORKER";
	/** 类型-质量员 */
	public static final String TYPE_QUALITY_WORKER = "QUALITY_WORKER";
	/** 类型-安全员 */
	public static final String TYPE_SAFETY_WORKER = "SAFETY_WORKER";
	/** 类型-预算员 */
	public static final String TYPE_BUDGETER = "BUDGETER";
	/** 类型-材料员 */
	public static final String TYPE_MATERIALMAN = "MATERIALMAN";
	/** 类型-机械员 */
	public static final String TYPE_MACHINIST = "MACHINIST";
	/** 类型-劳务员 */
	public static final String TYPE_LABOR_WORKER = "LABOR_WORKER";
	/** 类型-资料员 */
	public static final String TYPE_DATA_PROCESSOR = "DATA_PROCESSOR";
	public static final List<String> TYPE_LIST = Arrays.asList(new String[] { TYPE_PROJECT_MANAGER, TYPE_TECHNICAL_DIRECTOR, TYPE_CONSTRUCTION_WORKER, TYPE_QUALITY_WORKER, TYPE_SAFETY_WORKER,
			TYPE_BUDGETER, TYPE_MATERIALMAN, TYPE_MACHINIST, TYPE_LABOR_WORKER, TYPE_DATA_PROCESSOR });
    /**
     * Database Column Remarks:
     *   项目角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   项目角色类型（项目经理：PROJECT_MANAGER，技术负责人：TECHNICAL_DIRECTOR，施工员：CONSTRUCTION_WORKER，质量员：QUALITY_WORKER，安全员：SAFETY_WORKER，预算员：BUDGETER，材料员：MATERIALMAN，机械员：MACHINIST，劳务员：LABOR_WORKER，资料员：DATA_PROCESSOR
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role.id
     *
     * @return the value of team_role.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role.id
     *
     * @param id the value for team_role.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role.company_id
     *
     * @return the value of team_role.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role.company_id
     *
     * @param companyId the value for team_role.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role.name
     *
     * @return the value of team_role.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role.name
     *
     * @param name the value for team_role.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role.type
     *
     * @return the value of team_role.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role.type
     *
     * @param type the value for team_role.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role.cst_create
     *
     * @return the value of team_role.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role.cst_create
     *
     * @param cstCreate the value for team_role.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role.cst_modified
     *
     * @return the value of team_role.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role.cst_modified
     *
     * @param cstModified the value for team_role.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_role
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}