package top.warmheart.workerunion.server.model;

import java.io.Serializable;
import java.math.BigInteger;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team_role_has_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TeamRoleHasPermission implements Serializable {
    /**
     * Database Column Remarks:
     *   项目角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role_has_permission.team_role_id
     *
     * @mbg.generated
     */
    private BigInteger teamRoleId;

    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_role_has_permission.permission_id
     *
     * @mbg.generated
     */
    private BigInteger permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team_role_has_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role_has_permission.team_role_id
     *
     * @return the value of team_role_has_permission.team_role_id
     *
     * @mbg.generated
     */
    public BigInteger getTeamRoleId() {
        return teamRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role_has_permission.team_role_id
     *
     * @param teamRoleId the value for team_role_has_permission.team_role_id
     *
     * @mbg.generated
     */
    public void setTeamRoleId(BigInteger teamRoleId) {
        this.teamRoleId = teamRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_role_has_permission.permission_id
     *
     * @return the value of team_role_has_permission.permission_id
     *
     * @mbg.generated
     */
    public BigInteger getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_role_has_permission.permission_id
     *
     * @param permissionId the value for team_role_has_permission.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(BigInteger permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_role_has_permission
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teamRoleId=").append(teamRoleId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}