package top.warmheart.workerunion.server.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 *
 *	增加字段累计产值sumValue
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table business_capacity_item
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BusinessCapacityItemDto implements Serializable {
    /**
     * Database Column Remarks:
     *   经营管理ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   年份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.year
     *
     * @mbg.generated
     */
    private Integer year;

    /**
     * Database Column Remarks:
     *   月份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.month
     *
     * @mbg.generated
     */
    private Integer month;

    /**
     * Database Column Remarks:
     *   产值（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.product_value
     *
     * @mbg.generated
     */
    private BigDecimal productValue;

    /**
     * Database Column Remarks:
     *   核定产值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.checked_value
     *
     * @mbg.generated
     */
    private BigDecimal checkedValue;
    private BigDecimal sumValue;
    /**
     * Database Column Remarks:
     *   是否核定标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.is_checked
     *
     * @mbg.generated
     */
    private Boolean checked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.staff_id
     *
     * @mbg.generated
     */
    private BigInteger staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.staff_name
     *
     * @mbg.generated
     */
    private String staffName;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_capacity_item.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_capacity_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.id
     *
     * @return the value of business_capacity_item.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.id
     *
     * @param id the value for business_capacity_item.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.company_id
     *
     * @return the value of business_capacity_item.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.company_id
     *
     * @param companyId the value for business_capacity_item.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.project_id
     *
     * @return the value of business_capacity_item.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.project_id
     *
     * @param projectId the value for business_capacity_item.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.year
     *
     * @return the value of business_capacity_item.year
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.year
     *
     * @param year the value for business_capacity_item.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.month
     *
     * @return the value of business_capacity_item.month
     *
     * @mbg.generated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.month
     *
     * @param month the value for business_capacity_item.month
     *
     * @mbg.generated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.product_value
     *
     * @return the value of business_capacity_item.product_value
     *
     * @mbg.generated
     */
    public BigDecimal getProductValue() {
        return productValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.product_value
     *
     * @param productValue the value for business_capacity_item.product_value
     *
     * @mbg.generated
     */
    public void setProductValue(BigDecimal productValue) {
        this.productValue = productValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.checked_value
     *
     * @return the value of business_capacity_item.checked_value
     *
     * @mbg.generated
     */
    public BigDecimal getCheckedValue() {
        return checkedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.checked_value
     *
     * @param checkedValue the value for business_capacity_item.checked_value
     *
     * @mbg.generated
     */
    public void setCheckedValue(BigDecimal checkedValue) {
        this.checkedValue = checkedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.is_checked
     *
     * @return the value of business_capacity_item.is_checked
     *
     * @mbg.generated
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.is_checked
     *
     * @param checked the value for business_capacity_item.is_checked
     *
     * @mbg.generated
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.staff_id
     *
     * @return the value of business_capacity_item.staff_id
     *
     * @mbg.generated
     */
    public BigInteger getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.staff_id
     *
     * @param staffId the value for business_capacity_item.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(BigInteger staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.staff_name
     *
     * @return the value of business_capacity_item.staff_name
     *
     * @mbg.generated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.staff_name
     *
     * @param staffName the value for business_capacity_item.staff_name
     *
     * @mbg.generated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.cst_modified
     *
     * @return the value of business_capacity_item.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.cst_modified
     *
     * @param cstModified the value for business_capacity_item.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_capacity_item.cst_create
     *
     * @return the value of business_capacity_item.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_capacity_item.cst_create
     *
     * @param cstCreate the value for business_capacity_item.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    public BigDecimal getSumValue() {
		return sumValue;
	}

	public void setSumValue(BigDecimal sumValue) {
		this.sumValue = sumValue;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_capacity_item
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", projectId=").append(projectId);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", productValue=").append(productValue);
        sb.append(", checkedValue=").append(checkedValue);
        sb.append(", sumValue=").append(sumValue);
        sb.append(", checked=").append(checked);
        sb.append(", staffId=").append(staffId);
        sb.append(", staffName=").append(staffName);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}