package top.warmheart.workerunion.server.dto;

import java.io.Serializable;
import java.math.BigInteger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * 增加字段staffName staffJobNo staffIdCardNo
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table certificate
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CertificateDto implements Serializable {
    /**
     * Database Column Remarks:
     *   证书ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   员工ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.staff_id
     *
     * @mbg.generated
     */
    private BigInteger staffId;
    private String staffName;
    private String staffJobNo;
    private String staffIdCardNo;
    
    /**
     * Database Column Remarks:
     *   证书类型ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_type_id
     *
     * @mbg.generated
     */
    private BigInteger certificateTypeId;

    /**
     * Database Column Remarks:
     *   证书类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_type_name
     *
     * @mbg.generated
     */
    private String certificateTypeName;

    /**
     * Database Column Remarks:
     *   证书系列名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.certificate_serie_name
     *
     * @mbg.generated
     */
    private String certificateSerieName;
    private BigInteger certificateSerieId;
    /**
     * Database Column Remarks:
     *   证书编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     * Database Column Remarks:
     *   有效期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.valid_date
     *
     * @mbg.generated
     */
    private Date validDate;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate.is_del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table certificate
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.id
     *
     * @return the value of certificate.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.id
     *
     * @param id the value for certificate.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.company_id
     *
     * @return the value of certificate.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.company_id
     *
     * @param companyId the value for certificate.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.staff_id
     *
     * @return the value of certificate.staff_id
     *
     * @mbg.generated
     */
    public BigInteger getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.staff_id
     *
     * @param staffId the value for certificate.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(BigInteger staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_type_id
     *
     * @return the value of certificate.certificate_type_id
     *
     * @mbg.generated
     */
    public BigInteger getCertificateTypeId() {
        return certificateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_type_id
     *
     * @param certificateTypeId the value for certificate.certificate_type_id
     *
     * @mbg.generated
     */
    public void setCertificateTypeId(BigInteger certificateTypeId) {
        this.certificateTypeId = certificateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_type_name
     *
     * @return the value of certificate.certificate_type_name
     *
     * @mbg.generated
     */
    public String getCertificateTypeName() {
        return certificateTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_type_name
     *
     * @param certificateTypeName the value for certificate.certificate_type_name
     *
     * @mbg.generated
     */
    public void setCertificateTypeName(String certificateTypeName) {
        this.certificateTypeName = certificateTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.certificate_serie_name
     *
     * @return the value of certificate.certificate_serie_name
     *
     * @mbg.generated
     */
    public String getCertificateSerieName() {
        return certificateSerieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.certificate_serie_name
     *
     * @param certificateSerieName the value for certificate.certificate_serie_name
     *
     * @mbg.generated
     */
    public void setCertificateSerieName(String certificateSerieName) {
        this.certificateSerieName = certificateSerieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.num
     *
     * @return the value of certificate.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.num
     *
     * @param num the value for certificate.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.valid_date
     *
     * @return the value of certificate.valid_date
     *
     * @mbg.generated
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.valid_date
     *
     * @param validDate the value for certificate.valid_date
     *
     * @mbg.generated
     */
    public void setValidDate(String validDate) throws ParseException {
        this.validDate = new SimpleDateFormat("yyyy-MM-dd").parse(validDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.cst_create
     *
     * @return the value of certificate.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.cst_create
     *
     * @param cstCreate the value for certificate.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.cst_modified
     *
     * @return the value of certificate.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.cst_modified
     *
     * @param cstModified the value for certificate.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate.is_del
     *
     * @return the value of certificate.is_del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate.is_del
     *
     * @param del the value for certificate.is_del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    public String getStaffName() {
		return staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public String getStaffJobNo() {
		return staffJobNo;
	}

	public void setStaffJobNo(String staffJobNo) {
		this.staffJobNo = staffJobNo;
	}

	public String getStaffIdCardNo() {
		return staffIdCardNo;
	}

	public void setStaffIdCardNo(String staffIdCardNo) {
		this.staffIdCardNo = staffIdCardNo;
	}

	public BigInteger getCertificateSerieId() {
		return certificateSerieId;
	}

	public void setCertificateSerieId(BigInteger certificateSerieId) {
		this.certificateSerieId = certificateSerieId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", staffId=").append(staffId);
        sb.append(", staffName=").append(staffName);
        sb.append(", staffJobNo=").append(staffJobNo);
        sb.append(", staffIdCardNo=").append(staffIdCardNo);
        sb.append(", certificateTypeId=").append(certificateTypeId);
        sb.append(", certificateTypeName=").append(certificateTypeName);
        sb.append(", certificateSerieId=").append(certificateSerieId);
        sb.append(", certificateSerieName=").append(certificateSerieName);
        sb.append(", num=").append(num);
        sb.append(", validDate=").append(validDate);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", del=").append(del);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}