package top.warmheart.workerunion.server.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 * 增加字段 projectName projectNum
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table contract
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ContractDto implements Serializable {
    /**
     * Database Column Remarks:
     *   合同ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;
    private String projectName;
    private String projectNum;
    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     * Database Column Remarks:
     *   类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   甲方名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.part_a
     *
     * @mbg.generated
     */
    private String partA;

    /**
     * Database Column Remarks:
     *   乙方名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.part_b
     *
     * @mbg.generated
     */
    private String partB;

    /**
     * Database Column Remarks:
     *   签约时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.sign_date
     *
     * @mbg.generated
     */
    private Date signDate;

    /**
     * Database Column Remarks:
     *   金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     * Database Column Remarks:
     *   责任部门
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.duty_department
     *
     * @mbg.generated
     */
    private String dutyDepartment;

    /**
     * Database Column Remarks:
     *   内容摘要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.content_abstract
     *
     * @mbg.generated
     */
    private String contentAbstract;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.is_del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.id
     *
     * @return the value of contract.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.id
     *
     * @param id the value for contract.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.company_id
     *
     * @return the value of contract.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.company_id
     *
     * @param companyId the value for contract.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.project_id
     *
     * @return the value of contract.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.project_id
     *
     * @param projectId the value for contract.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.name
     *
     * @return the value of contract.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.name
     *
     * @param name the value for contract.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.num
     *
     * @return the value of contract.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.num
     *
     * @param num the value for contract.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.type
     *
     * @return the value of contract.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.type
     *
     * @param type the value for contract.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.part_a
     *
     * @return the value of contract.part_a
     *
     * @mbg.generated
     */
    public String getPartA() {
        return partA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.part_a
     *
     * @param partA the value for contract.part_a
     *
     * @mbg.generated
     */
    public void setPartA(String partA) {
        this.partA = partA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.part_b
     *
     * @return the value of contract.part_b
     *
     * @mbg.generated
     */
    public String getPartB() {
        return partB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.part_b
     *
     * @param partB the value for contract.part_b
     *
     * @mbg.generated
     */
    public void setPartB(String partB) {
        this.partB = partB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.sign_date
     *
     * @return the value of contract.sign_date
     *
     * @mbg.generated
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.sign_date
     *
     * @param signDate the value for contract.sign_date
     *
     * @mbg.generated
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.money
     *
     * @return the value of contract.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.money
     *
     * @param money the value for contract.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.duty_department
     *
     * @return the value of contract.duty_department
     *
     * @mbg.generated
     */
    public String getDutyDepartment() {
        return dutyDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.duty_department
     *
     * @param dutyDepartment the value for contract.duty_department
     *
     * @mbg.generated
     */
    public void setDutyDepartment(String dutyDepartment) {
        this.dutyDepartment = dutyDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.content_abstract
     *
     * @return the value of contract.content_abstract
     *
     * @mbg.generated
     */
    public String getContentAbstract() {
        return contentAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.content_abstract
     *
     * @param contentAbstract the value for contract.content_abstract
     *
     * @mbg.generated
     */
    public void setContentAbstract(String contentAbstract) {
        this.contentAbstract = contentAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.cst_create
     *
     * @return the value of contract.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.cst_create
     *
     * @param cstCreate the value for contract.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.cst_modified
     *
     * @return the value of contract.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.cst_modified
     *
     * @param cstModified the value for contract.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.is_del
     *
     * @return the value of contract.is_del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.is_del
     *
     * @param del the value for contract.is_del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectNum() {
		return projectNum;
	}

	public void setProjectNum(String projectNum) {
		this.projectNum = projectNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", projectId=").append(projectId);
        sb.append(", projectNum=").append(projectNum);
        sb.append(", projectName=").append(projectName);
        sb.append(", name=").append(name);
        sb.append(", num=").append(num);
        sb.append(", type=").append(type);
        sb.append(", partA=").append(partA);
        sb.append(", partB=").append(partB);
        sb.append(", signDate=").append(signDate);
        sb.append(", money=").append(money);
        sb.append(", dutyDepartment=").append(dutyDepartment);
        sb.append(", contentAbstract=").append(contentAbstract);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", del=").append(del);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}