package top.warmheart.workerunion.server.dto;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;

/**
 * 增加projectNum projectName
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table safety_check_item
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SafetyCheckItemDto implements Serializable {/**
	 * Database Column Remarks: 安全检查ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.id
	 *
	 * @mbg.generated
	 */
	private BigInteger id;
	private String projectNum;
	private String projectName;
	
	public String getProjectNum() {
		return projectNum;
	}

	public void setProjectNum(String projectNum) {
		this.projectNum = projectNum;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * Database Column Remarks: 企业ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.company_id
	 *
	 * @mbg.generated
	 */
	private BigInteger companyId;

	/**
	 * Database Column Remarks: 项目ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.project_id
	 *
	 * @mbg.generated
	 */
	private BigInteger projectId;

	/**
	 * Database Column Remarks: 检查日期
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.inspect_date
	 *
	 * @mbg.generated
	 */
	private Date inspectDate;

	/**
	 * Database Column Remarks: 检查记录
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.inspect_record
	 *
	 * @mbg.generated
	 */
	private String inspectRecord;

	/**
	 * Database Column Remarks: 整改意见
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.rectify_opinion
	 *
	 * @mbg.generated
	 */
	private String rectifyOpinion;

	/**
	 * Database Column Remarks: 项目反馈
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.project_feedback
	 *
	 * @mbg.generated
	 */
	private String projectFeedback;

	/**
	 * Database Column Remarks: 评定日期
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.evaluate_date
	 *
	 * @mbg.generated
	 */
	private Date evaluateDate;

	/**
	 * Database Column Remarks: 检查评定
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.evaluate
	 *
	 * @mbg.generated
	 */
	private String evaluate;

	/**
	 * Database Column Remarks: 整改状态（整改通过：PASS，整改：RECTIFY，整改申请审核：VERIFY）
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.rectify_status
	 *
	 * @mbg.generated
	 */
	private String rectifyStatus;

	/**
	 * Database Column Remarks: 检查人ID
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.staff_id
	 *
	 * @mbg.generated
	 */
	private BigInteger staffId;

	/**
	 * Database Column Remarks: 检查人名称
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.staff_name
	 *
	 * @mbg.generated
	 */
	private String staffName;

	/**
	 * Database Column Remarks: 创建时间
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.cst_create
	 *
	 * @mbg.generated
	 */
	private Date cstCreate;

	/**
	 * Database Column Remarks: 修改时间
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.cst_modified
	 *
	 * @mbg.generated
	 */
	private Date cstModified;

	/**
	 * Database Column Remarks: 删除标识
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column safety_check_item.is_del
	 *
	 * @mbg.generated
	 */
	private Boolean del;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table safety_check_item
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.id
	 *
	 * @return the value of safety_check_item.id
	 *
	 * @mbg.generated
	 */
	public BigInteger getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.id
	 *
	 * @param id
	 *            the value for safety_check_item.id
	 *
	 * @mbg.generated
	 */
	public void setId(BigInteger id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.company_id
	 *
	 * @return the value of safety_check_item.company_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.company_id
	 *
	 * @param companyId
	 *            the value for safety_check_item.company_id
	 *
	 * @mbg.generated
	 */
	public void setCompanyId(BigInteger companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.project_id
	 *
	 * @return the value of safety_check_item.project_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.project_id
	 *
	 * @param projectId
	 *            the value for safety_check_item.project_id
	 *
	 * @mbg.generated
	 */
	public void setProjectId(BigInteger projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.inspect_date
	 *
	 * @return the value of safety_check_item.inspect_date
	 *
	 * @mbg.generated
	 */
	public Date getInspectDate() {
		return inspectDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.inspect_date
	 *
	 * @param inspectDate
	 *            the value for safety_check_item.inspect_date
	 *
	 * @mbg.generated
	 */
	public void setInspectDate(Date inspectDate) {
		this.inspectDate = inspectDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.inspect_record
	 *
	 * @return the value of safety_check_item.inspect_record
	 *
	 * @mbg.generated
	 */
	public String getInspectRecord() {
		return inspectRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.inspect_record
	 *
	 * @param inspectRecord
	 *            the value for safety_check_item.inspect_record
	 *
	 * @mbg.generated
	 */
	public void setInspectRecord(String inspectRecord) {
		this.inspectRecord = inspectRecord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.rectify_opinion
	 *
	 * @return the value of safety_check_item.rectify_opinion
	 *
	 * @mbg.generated
	 */
	public String getRectifyOpinion() {
		return rectifyOpinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.rectify_opinion
	 *
	 * @param rectifyOpinion
	 *            the value for safety_check_item.rectify_opinion
	 *
	 * @mbg.generated
	 */
	public void setRectifyOpinion(String rectifyOpinion) {
		this.rectifyOpinion = rectifyOpinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.project_feedback
	 *
	 * @return the value of safety_check_item.project_feedback
	 *
	 * @mbg.generated
	 */
	public String getProjectFeedback() {
		return projectFeedback;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.project_feedback
	 *
	 * @param projectFeedback
	 *            the value for safety_check_item.project_feedback
	 *
	 * @mbg.generated
	 */
	public void setProjectFeedback(String projectFeedback) {
		this.projectFeedback = projectFeedback;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.evaluate_date
	 *
	 * @return the value of safety_check_item.evaluate_date
	 *
	 * @mbg.generated
	 */
	public Date getEvaluateDate() {
		return evaluateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.evaluate_date
	 *
	 * @param evaluateDate
	 *            the value for safety_check_item.evaluate_date
	 *
	 * @mbg.generated
	 */
	public void setEvaluateDate(Date evaluateDate) {
		this.evaluateDate = evaluateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.evaluate
	 *
	 * @return the value of safety_check_item.evaluate
	 *
	 * @mbg.generated
	 */
	public String getEvaluate() {
		return evaluate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.evaluate
	 *
	 * @param evaluate
	 *            the value for safety_check_item.evaluate
	 *
	 * @mbg.generated
	 */
	public void setEvaluate(String evaluate) {
		this.evaluate = evaluate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.rectify_status
	 *
	 * @return the value of safety_check_item.rectify_status
	 *
	 * @mbg.generated
	 */
	public String getRectifyStatus() {
		return rectifyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.rectify_status
	 *
	 * @param rectifyStatus
	 *            the value for safety_check_item.rectify_status
	 *
	 * @mbg.generated
	 */
	public void setRectifyStatus(String rectifyStatus) {
		this.rectifyStatus = rectifyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.staff_id
	 *
	 * @return the value of safety_check_item.staff_id
	 *
	 * @mbg.generated
	 */
	public BigInteger getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.staff_id
	 *
	 * @param staffId
	 *            the value for safety_check_item.staff_id
	 *
	 * @mbg.generated
	 */
	public void setStaffId(BigInteger staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.staff_name
	 *
	 * @return the value of safety_check_item.staff_name
	 *
	 * @mbg.generated
	 */
	public String getStaffName() {
		return staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.staff_name
	 *
	 * @param staffName
	 *            the value for safety_check_item.staff_name
	 *
	 * @mbg.generated
	 */
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.cst_create
	 *
	 * @return the value of safety_check_item.cst_create
	 *
	 * @mbg.generated
	 */
	public Date getCstCreate() {
		return cstCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.cst_create
	 *
	 * @param cstCreate
	 *            the value for safety_check_item.cst_create
	 *
	 * @mbg.generated
	 */
	public void setCstCreate(Date cstCreate) {
		this.cstCreate = cstCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.cst_modified
	 *
	 * @return the value of safety_check_item.cst_modified
	 *
	 * @mbg.generated
	 */
	public Date getCstModified() {
		return cstModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.cst_modified
	 *
	 * @param cstModified
	 *            the value for safety_check_item.cst_modified
	 *
	 * @mbg.generated
	 */
	public void setCstModified(Date cstModified) {
		this.cstModified = cstModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column safety_check_item.is_del
	 *
	 * @return the value of safety_check_item.is_del
	 *
	 * @mbg.generated
	 */
	public Boolean getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column safety_check_item.is_del
	 *
	 * @param del
	 *            the value for safety_check_item.is_del
	 *
	 * @mbg.generated
	 */
	public void setDel(Boolean del) {
		this.del = del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table safety_check_item
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", companyId=").append(companyId);
		sb.append(", projectId=").append(projectId);
		sb.append(", inspectDate=").append(inspectDate);
		sb.append(", inspectRecord=").append(inspectRecord);
		sb.append(", rectifyOpinion=").append(rectifyOpinion);
		sb.append(", projectFeedback=").append(projectFeedback);
		sb.append(", evaluateDate=").append(evaluateDate);
		sb.append(", evaluate=").append(evaluate);
		sb.append(", rectifyStatus=").append(rectifyStatus);
		sb.append(", staffId=").append(staffId);
		sb.append(", staffName=").append(staffName);
		sb.append(", cstCreate=").append(cstCreate);
		sb.append(", cstModified=").append(cstModified);
		sb.append(", del=").append(del);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}