package top.warmheart.workerunion.server.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 * 增加字段 resourceImplementItemName/resourceImplementItemMoney
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table settlement_item
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SettlementItem2Dto implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.id
     *
     * @mbg.generated
     */
    private BigInteger id;

    /**
     * Database Column Remarks:
     *   企业ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.company_id
     *
     * @mbg.generated
     */
    private BigInteger companyId;

    /**
     * Database Column Remarks:
     *   项目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.project_id
     *
     * @mbg.generated
     */
    private BigInteger projectId;

    /**
     * Database Column Remarks:
     *   资源落实项ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.resource_implement_item_id
     *
     * @mbg.generated
     */
    private BigInteger resourceImplementItemId;
    private String resourceImplementItemName;
    private BigDecimal resourceImplementItemMoney;
    /**
     * Database Column Remarks:
     *   分包商ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.subcontractor_id
     *
     * @mbg.generated
     */
    private BigInteger subcontractorId;

    /**
     * Database Column Remarks:
     *   分包商名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.subcontractor_name
     *
     * @mbg.generated
     */
    private String subcontractorName;

    /**
     * Database Column Remarks:
     *   采购条目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.purchase_item_id
     *
     * @mbg.generated
     */
    private BigInteger purchaseItemId;

    /**
     * Database Column Remarks:
     *   采购条目名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.purchase_item_name
     *
     * @mbg.generated
     */
    private String purchaseItemName;

    /**
     * Database Column Remarks:
     *   年份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.year
     *
     * @mbg.generated
     */
    private Integer year;

    /**
     * Database Column Remarks:
     *   月份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.month
     *
     * @mbg.generated
     */
    private Integer month;

    /**
     * Database Column Remarks:
     *   当月结算值（单位：元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.money
     *
     * @mbg.generated
     */
    private BigDecimal money;
    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.cst_create
     *
     * @mbg.generated
     */
    private Date cstCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlement_item.cst_modified
     *
     * @mbg.generated
     */
    private Date cstModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table settlement_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.id
     *
     * @return the value of settlement_item.id
     *
     * @mbg.generated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.id
     *
     * @param id the value for settlement_item.id
     *
     * @mbg.generated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.company_id
     *
     * @return the value of settlement_item.company_id
     *
     * @mbg.generated
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.company_id
     *
     * @param companyId the value for settlement_item.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.project_id
     *
     * @return the value of settlement_item.project_id
     *
     * @mbg.generated
     */
    public BigInteger getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.project_id
     *
     * @param projectId the value for settlement_item.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.resource_implement_item_id
     *
     * @return the value of settlement_item.resource_implement_item_id
     *
     * @mbg.generated
     */
    public BigInteger getResourceImplementItemId() {
        return resourceImplementItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.resource_implement_item_id
     *
     * @param resourceImplementItemId the value for settlement_item.resource_implement_item_id
     *
     * @mbg.generated
     */
    public void setResourceImplementItemId(BigInteger resourceImplementItemId) {
        this.resourceImplementItemId = resourceImplementItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.subcontractor_id
     *
     * @return the value of settlement_item.subcontractor_id
     *
     * @mbg.generated
     */
    public BigInteger getSubcontractorId() {
        return subcontractorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.subcontractor_id
     *
     * @param subcontractorId the value for settlement_item.subcontractor_id
     *
     * @mbg.generated
     */
    public void setSubcontractorId(BigInteger subcontractorId) {
        this.subcontractorId = subcontractorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.subcontractor_name
     *
     * @return the value of settlement_item.subcontractor_name
     *
     * @mbg.generated
     */
    public String getSubcontractorName() {
        return subcontractorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.subcontractor_name
     *
     * @param subcontractorName the value for settlement_item.subcontractor_name
     *
     * @mbg.generated
     */
    public void setSubcontractorName(String subcontractorName) {
        this.subcontractorName = subcontractorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.purchase_item_id
     *
     * @return the value of settlement_item.purchase_item_id
     *
     * @mbg.generated
     */
    public BigInteger getPurchaseItemId() {
        return purchaseItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.purchase_item_id
     *
     * @param purchaseItemId the value for settlement_item.purchase_item_id
     *
     * @mbg.generated
     */
    public void setPurchaseItemId(BigInteger purchaseItemId) {
        this.purchaseItemId = purchaseItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.purchase_item_name
     *
     * @return the value of settlement_item.purchase_item_name
     *
     * @mbg.generated
     */
    public String getPurchaseItemName() {
        return purchaseItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.purchase_item_name
     *
     * @param purchaseItemName the value for settlement_item.purchase_item_name
     *
     * @mbg.generated
     */
    public void setPurchaseItemName(String purchaseItemName) {
        this.purchaseItemName = purchaseItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.year
     *
     * @return the value of settlement_item.year
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.year
     *
     * @param year the value for settlement_item.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.month
     *
     * @return the value of settlement_item.month
     *
     * @mbg.generated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.month
     *
     * @param month the value for settlement_item.month
     *
     * @mbg.generated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.money
     *
     * @return the value of settlement_item.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.money
     *
     * @param money the value for settlement_item.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.cst_create
     *
     * @return the value of settlement_item.cst_create
     *
     * @mbg.generated
     */
    public Date getCstCreate() {
        return cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.cst_create
     *
     * @param cstCreate the value for settlement_item.cst_create
     *
     * @mbg.generated
     */
    public void setCstCreate(Date cstCreate) {
        this.cstCreate = cstCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlement_item.cst_modified
     *
     * @return the value of settlement_item.cst_modified
     *
     * @mbg.generated
     */
    public Date getCstModified() {
        return cstModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlement_item.cst_modified
     *
     * @param cstModified the value for settlement_item.cst_modified
     *
     * @mbg.generated
     */
    public void setCstModified(Date cstModified) {
        this.cstModified = cstModified;
    }

	public String getResourceImplementItemName() {
		return resourceImplementItemName;
	}

	public void setResourceImplementItemName(String resourceImplementItemName) {
		this.resourceImplementItemName = resourceImplementItemName;
	}

	public BigDecimal getResourceImplementItemMoney() {
		return resourceImplementItemMoney;
	}

	public void setResourceImplementItemMoney(BigDecimal resourceImplementItemMoney) {
		this.resourceImplementItemMoney = resourceImplementItemMoney;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement_item
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", projectId=").append(projectId);
        sb.append(", resourceImplementItemId=").append(resourceImplementItemId);
        sb.append(", resourceImplementItemName=").append(resourceImplementItemName);
        sb.append(", resourceImplementItemMoney=").append(resourceImplementItemMoney);
        sb.append(", subcontractorId=").append(subcontractorId);
        sb.append(", subcontractorName=").append(subcontractorName);
        sb.append(", purchaseItemId=").append(purchaseItemId);
        sb.append(", purchaseItemName=").append(purchaseItemName);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", money=").append(money);
        sb.append(", cstCreate=").append(cstCreate);
        sb.append(", cstModified=").append(cstModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}